// vue_study/vue_mac/src/App.vue
<template>
  <div id="app">
    <Header />
    <div id="content" class="content">
      <router-view></router-view>
    </div>
  </div>
</template>

<script>
import Header from './components/layout/Header.vue';

export default {
  name: 'App',
  components: {
    Header
  }
}
</script>

<style>

</style>

// react_study/fastcampus/11.prototype-shop/src/App.js
import Footer from './components/Footer';
import Header from './components/Header';
import Orders from './components/Orders';
import Prototypes from './components/Prototypes';

function App() {
    return (
        <>
            <Header />
            <div className="container">
                <Prototypes />
                <Orders />
                <Footer />
            </div>
        </>
    );
}

export default App;
